FROM python:3.13-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app/ab_test_platform

ENV PYTHONPATH=/app

CMD ["python", "-m", "ab_test_platform.src.main"]
